# -*- coding: utf-8 -*-

import contextlib
import importlib
import io

FUTURE_ACCOUNT = 1
SECURITY_ACCOUNT = 2
STOCK_ACCOUNT = SECURITY_ACCOUNT
CREDIT_ACCOUNT = 3
FUTURE_OPTION_ACCOUNT = 5
STOCK_OPTION_ACCOUNT = 6
HUGANGTONG_ACCOUNT = 7
INCOME_SWAP_ACCOUNT = 8
NEW3BOARD_ACCOUNT = 10
SHENGANGTONG_ACCOUNT = 11
AT_OFFSITEBANKING = 13
AT_OUTTER_FUTURE = 1001
AT_IB = 1002
AT_NS_TRUSTBANK = 15001
AT_INTERBANK = 15002
AT_BANK = 15003
AT_OTC = 15005

ACCOUNT_TYPE_DICT = {
    1: "FUTURE",
    2: "STOCK",
    3: "CREDIT",
    5: "FUTURE_OPTION",
    6: "STOCK_OPTION",
    7: "HUGANGTONG",
    8: "INCOME_SWAP",
    10: "NEW3BOARD",
    11: "SHENGANGTONG",
    13: "OFFSITEBANKING",
    1001: "OUTTER_FUTURE",
    1002: "IB",
    15001: "NS_TRUSTBANK",
    15002: "INTERBANK",
    15003: "BANK",
    15005: "OTC",
}

STOCK_BUY = 23
STOCK_SELL = 24
CREDIT_BUY = 23
CREDIT_SELL = 24
CREDIT_FIN_BUY = 27
CREDIT_SLO_SELL = 28
CREDIT_BUY_SECU_REPAY = 29
CREDIT_DIRECT_SECU_REPAY = 30
CREDIT_SELL_SECU_REPAY = 31
CREDIT_DIRECT_CASH_REPAY = 32
CREDIT_FIN_BUY_SPECIAL = 40
CREDIT_SLO_SELL_SPECIAL = 41
CREDIT_BUY_SECU_REPAY_SPECIAL = 42
CREDIT_DIRECT_SECU_REPAY_SPECIAL = 43
CREDIT_SELL_SECU_REPAY_SPECIAL = 44
CREDIT_DIRECT_CASH_REPAY_SPECIAL = 45
QMT_CREDIT_BUY = 33
QMT_CREDIT_SELL = 34
QMT_CREDIT_FIN_BUY_SPECIAL = 70
QMT_CREDIT_SLO_SELL_SPECIAL = 71
QMT_CREDIT_BUY_SECU_REPAY_SPECIAL = 72
QMT_CREDIT_DIRECT_SECU_REPAY_SPECIAL = 73
QMT_CREDIT_SELL_SECU_REPAY_SPECIAL = 74
QMT_CREDIT_DIRECT_CASH_REPAY_SPECIAL = 75
QMT_CREDIT_ORDER_TYPE_MAP = {
    CREDIT_BUY: QMT_CREDIT_BUY,
    CREDIT_SELL: QMT_CREDIT_SELL,
    CREDIT_FIN_BUY: CREDIT_FIN_BUY,
    CREDIT_SLO_SELL: CREDIT_SLO_SELL,
    CREDIT_BUY_SECU_REPAY: CREDIT_BUY_SECU_REPAY,
    CREDIT_DIRECT_SECU_REPAY: CREDIT_DIRECT_SECU_REPAY,
    CREDIT_SELL_SECU_REPAY: CREDIT_SELL_SECU_REPAY,
    CREDIT_DIRECT_CASH_REPAY: CREDIT_DIRECT_CASH_REPAY,
    CREDIT_FIN_BUY_SPECIAL: QMT_CREDIT_FIN_BUY_SPECIAL,
    CREDIT_SLO_SELL_SPECIAL: QMT_CREDIT_SLO_SELL_SPECIAL,
    CREDIT_BUY_SECU_REPAY_SPECIAL: QMT_CREDIT_BUY_SECU_REPAY_SPECIAL,
    CREDIT_DIRECT_SECU_REPAY_SPECIAL: QMT_CREDIT_DIRECT_SECU_REPAY_SPECIAL,
    CREDIT_SELL_SECU_REPAY_SPECIAL: QMT_CREDIT_SELL_SECU_REPAY_SPECIAL,
    CREDIT_DIRECT_CASH_REPAY_SPECIAL: QMT_CREDIT_DIRECT_CASH_REPAY_SPECIAL,
}
FUTURE_OPEN_LONG = 0
FUTURE_CLOSE_LONG_HISTORY = 1
FUTURE_CLOSE_LONG_TODAY = 2
FUTURE_OPEN_SHORT = 3
FUTURE_CLOSE_SHORT_HISTORY = 4
FUTURE_CLOSE_SHORT_TODAY = 5
FUTURE_CLOSE_LONG_TODAY_FIRST = 6
FUTURE_CLOSE_LONG_HISTORY_FIRST = 7
FUTURE_CLOSE_SHORT_TODAY_FIRST = 8
FUTURE_CLOSE_SHORT_HISTORY_FIRST = 9
FUTURE_CLOSE_LONG_TODAY_HISTORY_THEN_OPEN_SHORT = 10
FUTURE_CLOSE_LONG_HISTORY_TODAY_THEN_OPEN_SHORT = 11
FUTURE_CLOSE_SHORT_TODAY_HISTORY_THEN_OPEN_LONG = 12
FUTURE_CLOSE_SHORT_HISTORY_TODAY_THEN_OPEN_LONG = 13
FUTURE_OPEN = 14
FUTURE_CLOSE = 15
FUTURE_ARBITRAGE_OPEN = 16
FUTURE_ARBITRAGE_CLOSE_HISTORY_FIRST = 17
FUTURE_ARBITRAGE_CLOSE_TODAY_FIRST = 18
FUTURE_RENEW_LONG_CLOSE_HISTORY_FIRST = 19
FUTURE_RENEW_LONG_CLOSE_TODAY_FIRST = 20
FUTURE_RENEW_SHORT_CLOSE_HISTORY_FIRST = 21
FUTURE_RENEW_SHORT_CLOSE_TODAY_FIRST = 22
STOCK_OPTION_BUY_OPEN = 48
STOCK_OPTION_SELL_CLOSE = 49
STOCK_OPTION_SELL_OPEN = 50
STOCK_OPTION_BUY_CLOSE = 51
STOCK_OPTION_COVERED_OPEN = 52
STOCK_OPTION_COVERED_CLOSE = 53
STOCK_OPTION_CALL_EXERCISE = 54
STOCK_OPTION_PUT_EXERCISE = 55
STOCK_OPTION_SECU_LOCK = 56
STOCK_OPTION_SECU_UNLOCK = 57
QMT_STOCK_OPTION_BUY_OPEN = 50
QMT_STOCK_OPTION_SELL_CLOSE = 51
QMT_STOCK_OPTION_SELL_OPEN = 52
QMT_STOCK_OPTION_BUY_CLOSE = 53
QMT_STOCK_OPTION_COVERED_OPEN = 54
QMT_STOCK_OPTION_COVERED_CLOSE = 55
QMT_STOCK_OPTION_CALL_EXERCISE = 56
QMT_STOCK_OPTION_PUT_EXERCISE = 57
QMT_STOCK_OPTION_SECU_LOCK = 58
QMT_STOCK_OPTION_SECU_UNLOCK = 59
QMT_STOCK_OPTION_ORDER_TYPE_MAP = {
    STOCK_OPTION_BUY_OPEN: QMT_STOCK_OPTION_BUY_OPEN,
    STOCK_OPTION_SELL_CLOSE: QMT_STOCK_OPTION_SELL_CLOSE,
    STOCK_OPTION_SELL_OPEN: QMT_STOCK_OPTION_SELL_OPEN,
    STOCK_OPTION_BUY_CLOSE: QMT_STOCK_OPTION_BUY_CLOSE,
    STOCK_OPTION_COVERED_OPEN: QMT_STOCK_OPTION_COVERED_OPEN,
    STOCK_OPTION_COVERED_CLOSE: QMT_STOCK_OPTION_COVERED_CLOSE,
    STOCK_OPTION_CALL_EXERCISE: QMT_STOCK_OPTION_CALL_EXERCISE,
    STOCK_OPTION_PUT_EXERCISE: QMT_STOCK_OPTION_PUT_EXERCISE,
    STOCK_OPTION_SECU_LOCK: QMT_STOCK_OPTION_SECU_LOCK,
    STOCK_OPTION_SECU_UNLOCK: QMT_STOCK_OPTION_SECU_UNLOCK,
}
OPTION_FUTURE_OPTION_EXERCISE = 100
COMPOSE_OPEN_LONG = 110
COMPOSE_OPEN_SHORT = 111
COMPOSE_CLOSE_LONG_TODAY_FIRST = 112
COMPOSE_CLOSE_LONG_HISTORY_FIRST = 113
COMPOSE_CLOSE_SHORT_TODAY_FIRST = 114
COMPOSE_CLOSE_SHORT_HISTORY_FIRST = 115
COMPOSE_ONEKEY_FUTURE_TODAY_FIRST = 116
COMPOSE_ONEKEY_FUTURE_HISTORY_FIRST = 117
COMPOSE_FUTURE_ADJUST_TODAY_FIRST = 118
COMPOSE_FUTURE_ADJUST_HISTORY_FIRST = 119
COMPOSE_OPTION_COMB_EXERCISE = 137
COMPOSE_OPTION_BUILD_COMB_STRATEGY = 138
COMPOSE_OPTION_RELEASE_COMB_STRATEGY = 139
FUTURE_HEDGE = 400
ETF_PURCHASE = 134
ETF_REDEMPTION = 135
ORDER_TYPE_SET = {
    STOCK_BUY,
    STOCK_SELL,
    CREDIT_BUY,
    CREDIT_SELL,
    CREDIT_FIN_BUY,
    CREDIT_SLO_SELL,
    CREDIT_BUY_SECU_REPAY,
    CREDIT_DIRECT_SECU_REPAY,
    CREDIT_SELL_SECU_REPAY,
    CREDIT_DIRECT_CASH_REPAY,
    CREDIT_FIN_BUY_SPECIAL,
    CREDIT_SLO_SELL_SPECIAL,
    CREDIT_BUY_SECU_REPAY_SPECIAL,
    CREDIT_DIRECT_SECU_REPAY_SPECIAL,
    CREDIT_SELL_SECU_REPAY_SPECIAL,
    CREDIT_DIRECT_CASH_REPAY_SPECIAL,
    QMT_CREDIT_BUY,
    QMT_CREDIT_SELL,
    QMT_CREDIT_FIN_BUY_SPECIAL,
    QMT_CREDIT_SLO_SELL_SPECIAL,
    QMT_CREDIT_BUY_SECU_REPAY_SPECIAL,
    QMT_CREDIT_DIRECT_SECU_REPAY_SPECIAL,
    QMT_CREDIT_SELL_SECU_REPAY_SPECIAL,
    QMT_CREDIT_DIRECT_CASH_REPAY_SPECIAL,
    FUTURE_OPEN_LONG,
    FUTURE_CLOSE_LONG_HISTORY,
    FUTURE_CLOSE_LONG_TODAY,
    FUTURE_OPEN_SHORT,
    FUTURE_CLOSE_SHORT_HISTORY,
    FUTURE_CLOSE_SHORT_TODAY,
    FUTURE_CLOSE_LONG_TODAY_FIRST,
    FUTURE_CLOSE_LONG_HISTORY_FIRST,
    FUTURE_CLOSE_SHORT_TODAY_FIRST,
    FUTURE_CLOSE_SHORT_HISTORY_FIRST,
    FUTURE_CLOSE_LONG_TODAY_HISTORY_THEN_OPEN_SHORT,
    FUTURE_CLOSE_LONG_HISTORY_TODAY_THEN_OPEN_SHORT,
    FUTURE_CLOSE_SHORT_TODAY_HISTORY_THEN_OPEN_LONG,
    FUTURE_CLOSE_SHORT_HISTORY_TODAY_THEN_OPEN_LONG,
    FUTURE_OPEN,
    FUTURE_CLOSE,
    FUTURE_ARBITRAGE_OPEN,
    FUTURE_ARBITRAGE_CLOSE_HISTORY_FIRST,
    FUTURE_ARBITRAGE_CLOSE_TODAY_FIRST,
    FUTURE_RENEW_LONG_CLOSE_HISTORY_FIRST,
    FUTURE_RENEW_LONG_CLOSE_TODAY_FIRST,
    FUTURE_RENEW_SHORT_CLOSE_HISTORY_FIRST,
    FUTURE_RENEW_SHORT_CLOSE_TODAY_FIRST,
    STOCK_OPTION_BUY_OPEN,
    STOCK_OPTION_SELL_CLOSE,
    STOCK_OPTION_SELL_OPEN,
    STOCK_OPTION_BUY_CLOSE,
    STOCK_OPTION_COVERED_OPEN,
    STOCK_OPTION_COVERED_CLOSE,
    STOCK_OPTION_CALL_EXERCISE,
    STOCK_OPTION_PUT_EXERCISE,
    STOCK_OPTION_SECU_LOCK,
    STOCK_OPTION_SECU_UNLOCK,
    QMT_STOCK_OPTION_BUY_OPEN,
    QMT_STOCK_OPTION_SELL_CLOSE,
    QMT_STOCK_OPTION_SELL_OPEN,
    QMT_STOCK_OPTION_BUY_CLOSE,
    QMT_STOCK_OPTION_COVERED_OPEN,
    QMT_STOCK_OPTION_COVERED_CLOSE,
    QMT_STOCK_OPTION_CALL_EXERCISE,
    QMT_STOCK_OPTION_PUT_EXERCISE,
    QMT_STOCK_OPTION_SECU_LOCK,
    QMT_STOCK_OPTION_SECU_UNLOCK,
    OPTION_FUTURE_OPTION_EXERCISE,
    COMPOSE_OPEN_LONG,
    COMPOSE_OPEN_SHORT,
    COMPOSE_CLOSE_LONG_TODAY_FIRST,
    COMPOSE_CLOSE_LONG_HISTORY_FIRST,
    COMPOSE_CLOSE_SHORT_TODAY_FIRST,
    COMPOSE_CLOSE_SHORT_HISTORY_FIRST,
    COMPOSE_ONEKEY_FUTURE_TODAY_FIRST,
    COMPOSE_ONEKEY_FUTURE_HISTORY_FIRST,
    COMPOSE_FUTURE_ADJUST_TODAY_FIRST,
    COMPOSE_FUTURE_ADJUST_HISTORY_FIRST,
    COMPOSE_OPTION_COMB_EXERCISE,
    COMPOSE_OPTION_BUILD_COMB_STRATEGY,
    COMPOSE_OPTION_RELEASE_COMB_STRATEGY,
    FUTURE_HEDGE,
}

FIX_PRICE = 11
LATEST_PRICE = 5
PRTP_FIX = FIX_PRICE
PRTP_LATEST = LATEST_PRICE
PRTP_MARKET = 12

MARKET_SHANGHAI = "SH"
MARKET_SHENZHEN = "SZ"
MARKET_BEIJING = "BJ"
MARKET_HONGKONG = "HK"
MARKET_SHANGHAI_HONGKONG_STOCK = "HGT"
MARKET_SHENZHEN_HONGKONG_STOCK = "SGT"
MARKET_SHANGHAI_FUTURE = "SF"
MARKET_DALIANG_FUTURE = "DF"
MARKET_ZHENGZHOU_FUTURE = "ZF"
MARKET_INDEX_FUTURE = "IF"
MARKET_INTL_ENERGY_FUTURE = "INE"
MARKET_GUANGZHOU_FUTURE = "GF"
MARKET_SHANGHAI_STOCK_OPTION = "SHO"
MARKET_SHENZHEN_STOCK_OPTION = "SZO"
SH_MARKET = 0
SZ_MARKET = 1
MARKET_ENUM_INDEX_FUTURE = 2
MARKET_ENUM_SHANGHAI_FUTURE = 3
MARKET_ENUM_DALIANG_FUTURE = 4
MARKET_ENUM_ZHENGZHOU_FUTURE = 5
MARKET_ENUM_INTL_ENERGY_FUTURE = 6
MARKET_ENUM_SHANGHAI_STOCK_OPTION = 7
MARKET_ENUM_SHENZHEN_STOCK_OPTION = 67
MARKET_ENUM_BEIJING = 70
MARKET_ENUM_GUANGZHOU_FUTURE = 75
MARKET_STR_TO_ENUM_MAPPING = {
    "SH": SH_MARKET,
    "SZ": SZ_MARKET,
    "BJ": MARKET_ENUM_BEIJING,
    "SF": MARKET_ENUM_SHANGHAI_FUTURE,
    "DF": MARKET_ENUM_DALIANG_FUTURE,
    "ZF": MARKET_ENUM_ZHENGZHOU_FUTURE,
    "IF": MARKET_ENUM_INDEX_FUTURE,
    "INE": MARKET_ENUM_INTL_ENERGY_FUTURE,
    "GF": MARKET_ENUM_GUANGZHOU_FUTURE,
    "SHO": MARKET_ENUM_SHANGHAI_STOCK_OPTION,
    "SZO": MARKET_ENUM_SHENZHEN_STOCK_OPTION,
}

MARKET_BEST = 18
MARKET_CANCEL = 19
MARKET_CANCEL_ALL = 20
MARKET_CANCEL_1 = 21
MARKET_CANCEL_5 = 22
MARKET_CONVERT_1 = 23
MARKET_CONVERT_5 = 24
MARKET_PEER_PRICE_FIRST = 44
MARKET_MINE_PRICE_FIRST = 45
MARKET_SZ_INSTBUSI_RESTCANCEL = 46
MARKET_SZ_CONVERT_5_CANCEL = 47
MARKET_SZ_FULL_OR_CANCEL = 48
MARKET_SH_CONVERT_5_CANCEL = 42
MARKET_SH_CONVERT_5_LIMIT = 43

ORDER_UNREPORTED = 48
ORDER_WAIT_REPORTING = 49
ORDER_REPORTED = 50
ORDER_REPORTED_CANCEL = 51
ORDER_PARTSUCC_CANCEL = 52
ORDER_PART_CANCEL = 53
ORDER_CANCELED = 54
ORDER_PART_SUCC = 55
ORDER_SUCCEEDED = 56
ORDER_JUNK = 57
ORDER_UNKNOWN = 255

DIRECTION_FLAG_BUY = 48
DIRECTION_FLAG_SELL = 49
DIRECTION_FLAG_LONG = 48
DIRECTION_FLAG_SHORT = 49
OFFSET_FLAG_OPEN = 48
OFFSET_FLAG_CLOSE = 49
OFFSET_FLAG_FORCECLOSE = 50
OFFSET_FLAG_CLOSETODAY = 51
OFFSET_FLAG_FORCEOFF = 53
OFFSET_FLAG_LOCALFORCECLOSE = 54

ACCOUNT_STATUS_OK = 0
ACCOUNT_STATUS_WAITING_LOGIN = 1
ACCOUNT_STATUSING = 2
ACCOUNT_STATUS_FAIL = 3
ACCOUNT_STATUS_INITING = 4
ACCOUNT_STATUS_CORRECTING = 5
ACCOUNT_STATUS_CLOSED = 6
ACCOUNT_STATUS_ASSIS_FAIL = 7
ACCOUNT_STATUS_DISABLEBYSYS = 8
ACCOUNT_STATUS_DISABLEBYUSER = 9
ACCOUNT_STATUS_INVALID = -1


_UPSTREAM_XTCONSTANT = None
_UPSTREAM_XTCONSTANT_LOADED = False


def _upstream_xtconstant_module():
    global _UPSTREAM_XTCONSTANT
    global _UPSTREAM_XTCONSTANT_LOADED
    if _UPSTREAM_XTCONSTANT_LOADED:
        return _UPSTREAM_XTCONSTANT
    _UPSTREAM_XTCONSTANT_LOADED = True
    try:
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            _UPSTREAM_XTCONSTANT = importlib.import_module("xtquant.xtconstant")
    except Exception:
        _UPSTREAM_XTCONSTANT = None
    return _UPSTREAM_XTCONSTANT


def _load_upstream_xtquant_constants():
    module = _upstream_xtconstant_module()
    if module is None:
        return
    for name in dir(module):
        if not name.isupper() or name.startswith("_") or name in globals():
            continue
        try:
            globals()[name] = getattr(module, name)
        except Exception:
            pass


def __getattr__(name):
    if name.isupper() and not name.startswith("_"):
        module = _upstream_xtconstant_module()
        if module is not None and hasattr(module, name):
            value = getattr(module, name)
            globals()[name] = value
            return value
    raise AttributeError("module %r has no attribute %r" % (__name__, name))

__all__ = sorted(name for name in globals() if name.isupper() and not name.startswith("_"))
